#! /bin/bash
#
# 10_triangle_pattern
#
# Ray Yao's example script: "10. Print a triangle pattern"
#

rows=9
for((x=1; x<=rows; x++))
do
    for((y=1; y<=rows - x; y++))
    do
        echo -n " "
    done
    for((y=1; y<=2*x-1; y++))
    do
        echo -n "*"
    done
    echo
done
