#! /usr/bin/bash
#
# animate_star 1.0.0, 2023-05-11
#
# Calls david_color multiple times for creating an animation effect.
#
# Bernd Storck, https://www.facebook.com/BStLinux/
#

colors[0]='black'
colors[1]='blue'
colors[2]='cyan'
colors[3]='green'
colors[3]='no-color'
colors[4]='yellow'
colors[5]='red'
colors[6]='purple'

color=0
fgColor="${colors[$color]}"

max=$(( ( $(tput cols) - 4 ) / 2 ))
color_steps=$(( (max - 17) / 8 ))

clear

for (( i=18; i<=max; i++ ))
do
  if (( i % color_steps == 0 )); then
    (( color++ ))
    fgColor="${colors[$color]}"
  fi
  [ "$i" -eq "$max" ] && fgColor='white'
  clear
  ./david_color "$i" "$fgColor"
  sleep .1s
done
